import { Orbitron, Inter } from "next/font/google";
import "./globals.css";

// Load fonts with CSS variables
const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// App-wide metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout wrapper
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${orbitron.variable} ${inter.variable}`}>
      <body
        className='font-inter antialiased text-white'
      >
        {children}
      </body>
    </html>
  );
}
